In [50]:
import pandas as pd
from pandas import DataFrame as df
import numpy as np
import os
import geopandas as gpd
import matplotlib.pyplot as plt
import datetime as dt
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from imblearn.under_sampling import RandomUnderSampler
from imblearn.over_sampling import RandomOverSampler

# Grid 별, 비오톱 별로 각각의 Model을 학습
## 이 때 Grid에서 너무 sparse 한 경우 Rule Based로 0으로 
## Sparse 기준

In [39]:
비오톱0=pd.read_csv('./비오톱유형0.csv',header=0,index_col=0)

# TRAIN TEST SPLIT

In [ ]:
## Grid 1만 일단 진행해보자
## TEST는 2020년 7월 데이터만을 기준으로 진행하자

# Oversampling

In [48]:
for i in range(0,6):
    비오톱=pd.read_csv('./비오톱유형%d.csv'%i,header=0,index_col=0)
    train_data=비오톱[비오톱.index<='2020-06-30']
    test_data=비오톱[비오톱.index>'2020-06-30']
    y=(train_data['단속건수']!=0).astype(int)
    X=train_data[['month', 'days', 'hour', '요일', '시간대', 'holiday']]
    x_samp,y_samp=RandomOverSampler().fit_sample(X,y)
    xgb=XGBClassifier()
    xgb.fit(x_samp,y_samp)
    print("Test data")
    y_test=(test_data['단속건수']!=0).astype(int)
    X_test=test_data[['month', 'days', 'hour', '요일', '시간대', 'holiday']]
    print(classification_report(y_test,xgb.predict(X_test)))
    print(confusion_matrix(y_test,xgb.predict(X_test),labels=[0,1]))
    xgb.save_model('./비오톱_%d_xgboost'%i)

Test data
              precision    recall  f1-score   support

           0       0.90      0.57      0.70       263
           1       0.34      0.77      0.47        74

    accuracy                           0.61       337
   macro avg       0.62      0.67      0.58       337
weighted avg       0.77      0.61      0.65       337

[[150 113]
 [ 17  57]]
Test data
              precision    recall  f1-score   support

           0       0.69      0.69      0.69       104
           1       0.86      0.86      0.86       233

    accuracy                           0.81       337
   macro avg       0.77      0.78      0.77       337
weighted avg       0.81      0.81      0.81       337

[[ 72  32]
 [ 33 200]]
Test data
              precision    recall  f1-score   support

           0       0.88      0.61      0.72       233
           1       0.48      0.81      0.60       104

    accuracy                           0.67       337
   macro avg       0.68      0.71      0.66       33

# UNDER SAMPLING

In [51]:
for i in range(0,6):
    비오톱=pd.read_csv('./비오톱유형%d.csv'%i,header=0,index_col=0)
    train_data=비오톱[비오톱.index<='2020-06-30']
    test_data=비오톱[비오톱.index>'2020-06-30']
    y=(train_data['단속건수']!=0).astype(int)
    X=train_data[['month', 'days', 'hour', '요일', '시간대', 'holiday']]
    x_samp,y_samp=RandomUnderSampler().fit_sample(X,y)
    xgb=XGBClassifier()
    xgb.fit(x_samp,y_samp)
    print("Test data")
    y_test=(test_data['단속건수']!=0).astype(int)
    X_test=test_data[['month', 'days', 'hour', '요일', '시간대', 'holiday']]
    print(classification_report(y_test,xgb.predict(X_test)))
    print(confusion_matrix(y_test,xgb.predict(X_test),labels=[0,1]))    

Test data
              precision    recall  f1-score   support

           0       0.89      0.53      0.66       263
           1       0.31      0.77      0.45        74

    accuracy                           0.58       337
   macro avg       0.60      0.65      0.56       337
weighted avg       0.76      0.58      0.62       337

[[139 124]
 [ 17  57]]
Test data
              precision    recall  f1-score   support

           0       0.65      0.66      0.66       104
           1       0.85      0.84      0.84       233

    accuracy                           0.79       337
   macro avg       0.75      0.75      0.75       337
weighted avg       0.79      0.79      0.79       337

[[ 69  35]
 [ 37 196]]
Test data
              precision    recall  f1-score   support

           0       0.87      0.59      0.71       233
           1       0.47      0.81      0.59       104

    accuracy                           0.66       337
   macro avg       0.67      0.70      0.65       33

In [86]:
xgb=XGBClassifier()
xgb.fit(x_samp,y_samp)
print(classification_report(y_test,xgb.predict(X_test)))
print(confusion_matrix(y_test,xgb.predict(X_test),labels=[0,1]))

              precision    recall  f1-score   support

           0       0.97      0.76      0.85    124881
           1       0.43      0.89      0.58     25485

    accuracy                           0.78    150366
   macro avg       0.70      0.82      0.72    150366
weighted avg       0.88      0.78      0.81    150366

[[94787 30094]
 [ 2805 22680]]
